DROP TABLE TB_DEVOLUCION;
/
CREATE TABLE TB_DEVOLUCION (
  ID_DEVOLUCION NUMBER CONSTRAINT BT_DEVOLUCION_ID_NN NOT NULL ENABLE
                       CONSTRAINT BT_DEVOLUCION_ID_PK PRIMARY KEY ENABLE,
  FECHA VARCHAR2(30)   CONSTRAINT BT_DEVOLUCION_FECHA_NN NOT NULL ENABLE,
  ID_PRESTAMO NUMBER   CONSTRAINT BT_DEVOLUCION_ID_PRESTAMO_NN NOT NULL ENABLE,
  CONSTRAINT BT_DEVOLUCION_ID_PRESTAMO_FK FOREIGN KEY (ID_PRESTAMO) REFERENCES BT_PRESTAMO(ID_PRESTAMO) 
)
/
CREATE SEQUENCE BT_DEVOLUCION_AUTO_INCREMENTAL START WITH 1;
/
CREATE OR REPLACE TRIGGER BT_DEVOLUCION_UI BEFORE INSERT ON TB_DEVOLUCION FOR EACH ROW
BEGIN
  SELECT BT_DEVOLUCION_AUTO_INCREMENTAL.NEXTVAL INTO :NEW.ID_DEVOLUCION FROM DUAL;
END;
/
ALTER TRIGGER BT_DEVOLUCION_UI ENABLE;
/