DROP TABLE BT_LIBRO;
/
CREATE TABLE BT_LIBRO (
  ID_LIBRO NUMBER                   CONSTRAINT BT_LIBRO_ID_NN NOT NULL ENABLE
                                    CONSTRAINT BT_LIBRO_ID_PK PRIMARY KEY ENABLE,
  NOMBRE VARCHAR2(30)               CONSTRAINT BT_LIBRO_NOMBRE_NN NOT NULL ENABLE,
  DESCRIPCION VARCHAR2(255)         CONSTRAINT BT_LIBRO_DESCRIPCION_NN NOT NULL ENABLE,
  PAGINAS NUMBER                    CONSTRAINT BT_LIBRO_PAGINAS_NN NOT NULL ENABLE,
  IDIOMA VARCHAR2(30)               CONSTRAINT BT_LIBRO_IDIMA_NN NOT NULL ENABLE,
  URL_PORTADA VARCHAR2(100)         CONSTRAINT BT_LIBRO_URL_PORTADA_NN NOT NULL ENABLE,
  FECHA_LANZAMIENTO VARCHAR2 (255)  CONSTRAINT BT_LIBRO_FCHA_LNZMNTO_NN NOT NULL ENABLE,
  ID_AUTOR NUMBER                   CONSTRAINT BT_LIBRO_ID_AUTOR_NN NOT NULL ENABLE,
  ID_CATEGORIA NUMBER               CONSTRAINT BT_LIBRO_ID_CATEGORIA_NN NOT NULL ENABLE,                       
  ID_EDITORIAL NUMBER               CONSTRAINT BT_LIBRO_ID_EDITORIAL_NN NOT NULL ENABLE,
  CONSTRAINT BT_LIBRO_ID_AUTOR_FK FOREIGN KEY (ID_AUTOR) REFERENCES BT_AUTOR(ID_AUTOR) ENABLE,
  CONSTRAINT BT_LIBRO_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES BT_CATEGORIA(ID_CATEGORIA) ENABLE,
  CONSTRAINT BT_LIBRO_ID_EDITORIAL_FK FOREIGN KEY (ID_EDITORIAL) REFERENCES BT_EDITORIAL(ID_EDITORIAL) ENABLE
);
/
CREATE SEQUENCE BT_LIBRO_AUTO_INCREMETAL start with 1;
/
CREATE OR REPLACE TRIGGER BT_LIBRO_IU BEFORE INSERT ON BT_LIBRO FOR EACH ROW
BEGIN 
  SELECT BT_LIBRO_AUTO_INCREMETAL.NEXTVAL into :NEW.ID_LIBRO FROM DUAL;
END;
/
ALTER TRIGGER BT_LIBRO_IU ENABLE;