DROP TABLE BT_AUTOR;
/
CREATE TABLE BT_AUTOR (
  ID_AUTOR NUMBER                   CONSTRAINT BT_AUTOR_NN NOT NULL ENABLE
                                    CONSTRAINT BT_AUTOR_ID_PK PRIMARY KEY ENABLE,
  NOMBRE VARCHAR2(30)               CONSTRAINT BT_AUTOR_NOMBRE_NN NOT NULL ENABLE,
  APELLIDO VARCHAR2 (255)           CONSTRAINT BT_AUTOR_APELLIDO_NN NOT NULL ENABLE,
  FECHA_NACIMIENTO VARCHAR2 (255)   CONSTRAINT BT_AUTOR_FCHA_NCMIENTO_NN NOT NULL ENABLE
);
/
CREATE SEQUENCE BT_AUTOR_AUTO_INCREMETAL start with 1;
/
CREATE OR REPLACE TRIGGER BT_AUTOR_IU BEFORE INSERT ON BT_AUTOR FOR EACH ROW
BEGIN 
  SELECT BT_AUTOR_AUTO_INCREMETAL.NEXTVAL into :NEW.ID_AUTOR FROM DUAL;
END;
/
ALTER TRIGGER BT_AUTOR_IU ENABLE;
/
INSERT INTO BT_AUTOR (NOMBRE, APELLIDO, FECHA_NACIMIENTO) VALUES('MICHAEL', 'RODRIGUEZ', '11-22-1999');