DROP TABLE BT_EDITORIAL;
/
CREATE TABLE BT_EDITORIAL (
  ID_EDITORIAL NUMBER         CONSTRAINT BT_EDITORIAL_ID_NN NOT NULL ENABLE
                              CONSTRAINT BT_EDITORIAL_ID_PK PRIMARY KEY ENABLE,
  NOMBRE VARCHAR2(30)         CONSTRAINT BT_EDITORIAL_NOMBRE_NN NOT NULL ENABLE
);
/
CREATE SEQUENCE BT_EDITORIAL_AUTO_INCREMETAL start with 1;
/
CREATE OR REPLACE TRIGGER BT_EDITORIAL_IU BEFORE INSERT ON BT_EDITORIAL FOR EACH ROW
BEGIN 
  SELECT BT_EDITORIAL_AUTO_INCREMETAL.NEXTVAL into :NEW.ID_EDITORIAL FROM DUAL;
END;
/
ALTER TRIGGER BT_EDITORIAL_IU ENABLE;
/
INSERT INTO BT_EDITORIAL (NOMBRE) VALUES('MISTICA');