DROP TABLE BT_PRESTAMO;
/
CREATE TABLE BT_PRESTAMO (
  ID_PRESTAMO NUMBER          CONSTRAINT BT_PRESTAMO_ID_NN NOT NULL ENABLE
                              CONSTRAINT BT_PRESTAMO_ID_PK PRIMARY KEY ENABLE,
  FECHA_PRESTAMO VARCHAR2(30) CONSTRAINT BT_PRSTMO_FCHA_NN NOT NULL ENABLE,
  ID_CLIENTE                  CONSTRAINT BT_PRSTMO_ID_CLIENTE_NN NOT NULL ENABLE,
  ID_LIBRO                    CONSTRAINT BT_PRSTMO_ID_LIBRO_NN NOT NULL ENABLE,
  CONSTRAINT BT_PRSTMO_ID_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES BT_CLIENTE(ID_CLIENTE) ENABLE,
  CONSTRAINT BT_PRSTMO_ID_LIBRO_FK FOREIGN KEY (ID_LIBRO) REFERENCES BT_LIBRO(ID_LIBRO) ENABLE
)
/
CREATE SEQUENCE BT_PRESTAMO_AUTO_INCREMENTAL START WITH 1;
/
CREATE OR REPLACE TRIGGER BT_PRESTAMO_UI BEFORE INSERT ON BT_PRESTAMO FOR EACH ROW
BEGIN 
  SELECT BT_PRESTAMO_AUTO_INCREMENTAL.NEXTVAL INTO :NEW.ID_PRESTAMO FROM DUAL;
END;
/
ALTER TRIGGER BT_PRESTAMO_UI ENABLE;
/